name: Deploy UI
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ['frontend/**']
    paths-ignore:
      - 'frontend/README.md'

jobs:
  deployment:
    environment:
      name: ui
      url: https://rustter-ui.fly.dev/
    name: Deploy UI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy
        run: |
          flyctl deploy \
            --config frontend/fly.toml \
            --dockerfile frontend/Dockerfile \
            --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
